### ISSUE TITLE
New release/hackage revision for GHC 9.6.1?

### ISSUE THREAD

**Issue by LaurentRDC** [lspitzner/pqueue#121]
Hello,

While the repository can be built with GHC 9.6.1, the last version released on Hackage (1.4.3.0) does not support GHC 9.6. Would it be possible to either make a new release, or a Hackage revision? That is required for a future release of the beam-* packages which support GHC 9.6 (https://github.com/haskell-beam/beam/pull/673)

**Comment by konsumlamm** [comment]
Yes, I think we should make a new release. @treeowl are you fine with making a new release as is or is there anything that you think should be done before that?

**Comment by treeowl** [comment]
I would like to resolve the question of mapping strictness in relation to #118 to avoid any unnecessary semantic churn (for `mapMonotonic`) or performance churn (for maps and lazy traversals generally).

**Comment by treeowl** [comment]
The other issue I consider a release blocker is #106 .
