### ISSUE TITLE
mapU vs. mapMonotonic

### ISSUE THREAD

**Issue by treeowl** [lspitzner/pqueue#122]
`Data.PQueue.Min` exposes a `mapU` function which is completely undocumented, and does not expose the more aptly named `mapMonotonic`. I believe we should expose `mapMonotonic`, and eventually deprecate `mapU`. `mapU` is *not* an "unordered" operation, as its name suggests; rather, it's a somewhat unsafe one.

**Comment by konsumlamm** [comment]
Agreed. `Data.PQueue.Max` also exposes a `mapU`, which is documented, but no `mapMonotonic` either. This seems like a mistake.
