### ISSUE TITLE
Support GHC 9.8

### ISSUE THREAD

**Issue by andreasabel** [lspitzner/pqueue#132]
https://github.com/agda/agda/actions/runs/6637739425/job/18032666711#step:9:15
> [__0] trying: Agda-2.6.5 (user goal)
> [__1] trying: pqueue-1.5.0.0 (dependency of Agda)
> [__2] rejecting: base-4.19.0.0/installed (conflict: pqueue => base>=4.8 && <4.19)

**Comment by konsumlamm** [comment]
Closed by #133.
