### ISSUE TITLE
Allow specifying priority function

### ISSUE THREAD

**Issue by jml** [lspitzner/pqueue#17]
Much of the time, I want to use a priority queue to manage things that *have* a priority, rather than *are* a priority. That is, their `Ord` implementations don't match the priority I want, but there's a function I can run on them to get the priority I want.

It would be nice if the library had an interface for such things.

**Comment by jml** [comment]
I just thought of a work-around:

```haskell
newtype WithPriority a = WithPriority { rank :: (a -> Int), item :: a }

instance Ord (WithPriority a) where
   x `compare` y = rank x `compare` rank y
```

Perhaps that is better.

**Comment by thielema** [comment]
On Tue, 28 Nov 2017, Jonathan Lange wrote:

> Much of the time, I want to use a priority queue to manage things that 
> have a priority, rather than are a priority. That is, their Ord 
> implementations don't match the priority I want, but there's a function 
> I can run on them to get the priority I want.

For things that have a priority, but are not priorities themselves, there 
are already Data.PQueue.Prio.Max and Data.PQueue.Prio.Min.

Using an arbitrary comparison function causes the problem that the library 
cannot enforce anymore that always the same comparison function is used 
for the same data structure.

Are your comparisons really arbitrary or is it the same function that 
depends on an additional parameter? If the latter case then you might 
encode this parameter in a type parameter and use reification to feed the 
data parameter to the type parameter.

**Comment by thielema** [comment]
On Tue, 28 Nov 2017, Jonathan Lange wrote:

> I just thought of a work-around:
> 
> newtype WithPriority a = WithPriority { rank :: (a -> Int), item :: a }

If the priority depends only on the item then you can insert the rank 
directly in the WithPriority record (which must be 'data' not 'newtype', 
btw.).

> instance Ord (WithPriority a) where
>    x `compare` y = rank x `compare` rank y
> 
> Perhaps that is better.

Your example does not work. It must be:

compare x y = compare (rank x (item x)) (rank y (item y))

That is, the rank function can be different for x and y. Thus you can 
write the rank directly to the record, as well.

**Comment by jml** [comment]
> For things that have a priority, but are not priorities themselves, there are already Data.PQueue.Prio.Max and Data.PQueue.Prio.Min.

Awesome, thanks. This is exactly what I want.

**Comment by lspitzner** [comment]
This seems to be answered/resolved.
