### ISSUE TITLE
adapt to GHC-8.0.1

### ISSUE THREAD

**Issue by amigalemming** [lspitzner/pqueue#2]
For GHC-8.0 you must raise the upper version bound on `base` to 4.10. I can at least compile `pqueue` using `ghc-8.0.0.20160109`.

**Comment by lspitzner** [comment]
@amigalemming is this urgent? otherwise i'd probably wait until at least the first RC to check stuff and bump bounds.

**Comment by amigalemming** [comment]
On Mon, 11 Jan 2016, lspitzner wrote:

> @amigalemming is this urgent? otherwise i'd probably wait until at least the first RC to check stuff and bump bounds.

I don't think it is urgent.

**Comment by HeinrichApfelmus** [comment]
Thanks for writing pqueue! I am depending on it in my reactive-banana package.

It looks like GHC 8 is around the corner, and people are beginning to adapt their packages. I found it very useful to use Travis CI for testing a package against various GHC versions. You just have to include a `.travis.yml` file in your github repo, and link your account to Travis CI. Here is an [example `.travis.yml` file that tests multiple GHC versions][1].

  [1]: https://github.com/HeinrichApfelmus/vault/blob/master/.travis.yml

**Comment by lspitzner** [comment]
@HeinrichApfelmus i am just doing tiny bits of maintenance; the real work was done by @lowasser.

master here has already updated bounds, but because the latest release works fine when using --allow-newer=base, i planned to wait with a hackage release until ghc is out, even though it is highly unlikely that any breakage will occur until then.

**Comment by asr** [comment]
The source tarballs for GHC 8.0.1 were released some days ago. Please release to Hackage the version supporting this version of GHC.

**Comment by asr** [comment]
FYI, GHC 8.0.1 was just released (see  [ANNOUNCE](https://mail.haskell.org/pipermail/glasgow-haskell-users/2016-May/026232.html)).

**Comment by lspitzner** [comment]
@asr 1.3.1.1 is pushed and on hackage. sorry that i did not react sooner; i will probably change my policy to "publish new version as soon as there are no problems with any rc".

**Comment by lspitzner** [comment]
(oh, i did already say "first RC" above. really should have done this sooner, sorry again.)

**Comment by asr** [comment]
Thanks for realising.

**Comment by lspitzner** [comment]
@asr fyi github does not notify when an issue is simply referenced. feel free to ping (actual comment on the issue) me if there is no reaction.
