### ISSUE TITLE
Flexible comparison queues

### ISSUE THREAD

**Issue by treeowl** [lspitzner/pqueue#34]
The underlying functions take `LEq` operators rather than `Ord` dictionaries, but this power is not available to users without `reflection`. We can expose it if we choose.

```haskell
-- Exported abstractly
newtype LE s a = LE (a -> a -> Bool)
type role LE nominal representational

-- Exported abstractly
newtype MinQueue s a = MinQueue (Internals.MinQueue a)
type role MinQueue nominal nominal
-- In principle, this should probably be nominal representational, but that will take some shenanigans

data SomeLE a = forall s. SomeLE (LE s a)

mkLE :: (a -> a -> Bool) -> SomeLE a
mkLE le = SomeLE (LE le)

empty :: MinQueue s a
insert :: LE s a -> a -> MinQueue s a -> MinQueue s a
union :: LE s a -> MinQueue s a -> MinQueue s a -> MinQueue s a
-- etc.
```

The idea is that opening the result of `mkLE` reveals a whole universe of queues whose elements are ordered by the same comparison operator.

**Comment by treeowl** [comment]
Admittedly, the ergonomics will be pretty lousy without reflection....

**Comment by treeowl** [comment]
Ooh, another option is record-as-module.

```Haskell
data PQIF s a = PQIF {
  empty :: MinQueue s a
  insert :: a -> MinQueue s a -> MinQueue s a
  ...
}
```

With record field punning and record wildcards, that could maybe be reasonable.

**Comment by konsumlamm** [comment]
If priority queues with custom comparison functions are desired, I think the most ergonomic way would be to just store the comparison function in the data structure itself, like
```hs
-- using a `compare` function would be more flexible than storing `<=` 
data MinQueue a = MinQueue (a -> a -> Ordering) !(Internals.MinQueue a)
```
This could be a small performance hit, but I'm not convinced this approach is the best idea anyway. Instead, I think all the internal functions should just use the `Ord` instance, like the exposed functions already do (see #22).

If people really want a different comparison function, they can create a `newtype` wrapper with the desired `Ord` instance. `MaxQueue`/`MaxPQueue` are already cases of this, using `Down` under the hood. The wrapping/unwrapping should be zero-cost, so no performance hit.

**Comment by treeowl** [comment]
@konsumlamm storing the comparison function in the data structure is a bit tricky, because you have to make sure it's impossible to merge data structures with different comparison functions (eek!). This can be fixed using phantom types, but that's a terrible user interface.

```haskell
newtype Leq p a = Leq (a -> a -> Bool) -- constructor not exported
type role Leq nominal nominal
data SomeLeq a = forall p. SomeLeq (Leq  p a)
mkLeq :: (a -> a -> Bool) -> SomeLeq a
mkLeq f = SomeLeq (Leq f)
data PQ p a = PQ (Leq p a) !(PriorityQueue a)
```

We should definitely also consider the opposite approach: forget about `Leq` altogether and just use `Ord`. This closes off the possibility of letting users supply orderings without reflection, but should make it easier to arrange for specialization to work out well.

**Comment by konsumlamm** [comment]
> @konsumlamm storing the comparison function in the data structure is a bit tricky, because you have to make sure it's impossible to merge data structures with different comparison functions (eek!). This can be fixed using phantom types, but that's a terrible user interface.
> 
> ```haskell
> newtype Leq p a = Leq (a -> a -> Bool) -- constructor not exported
> type role Leq nominal nominal
> data SomeLeq a = forall p. SomeLeq (Leq  p a)
> mkLeq :: (a -> a -> Bool) -> SomeLeq a
> mkLeq f = SomeLeq (Leq f)
> data PQ p a = PQ (Leq p a) !(PriorityQueue a)
> ```

I don't quite understand how that would prevent queues with different `Leq`s from getting merged. How would a `PQ p a` be created with this interface?

> We should definitely also consider the opposite approach: forget about `Leq` altogether and just use `Ord`. This closes off the possibility of letting users supply orderings without reflection, but should make it easier to arrange for specialization to work out well.

Yeah, that's my preferred option, see also #22. The current interface only exposes `Ord` constraints anyway, so it wouldn't break anything. Fwiw, `Data.Map` and `Data.Set` (from `containers`) don't support anything like this either and I don't think it'd be a particularly useful feature.

**Comment by treeowl** [comment]
> I don't quite understand how that would prevent queues with different `Leq`s from getting merged. How would a `PQ p a` be created with this interface?

As I said, I don't really think we want that, because the ergonomics wouldn't be great. Two queues with different `Leq`s wouldn't have the same type. You'd write something like, say,

```haskell
case mkLeq myLte of { SomeLeq lte ->
  let
    this_queue = fromList lte [blah, blah, blah]
    that_queue = fromList lte [yada, yada, yada]
    yoohoo = union this_queue that_queue
    frobnicoz = toList yoohoo
  in yolo
  }
```

Each pattern match on a call to `mkLeq` produces a brand new `p` type that won't match anything else, so it's totally safe. It's just really painful. Note also that functions that produce queues without consuming them need to take the comparison as an argument. Meh.

One alternative approach to using a custom comparison, which is *somewhat* more ergonomical, is to use `reflection`. Instead of using `mkLeq`, you'd use a newtype something like (not actually tested)

```haskell
newtype Named p a = Named a

instance Reifies p (a -> a -> Bool) => Ord (Named p a) where
  (<=) = coerce (reflect (Proxy @p))
```

Now you'd work under the scope of `reify`:

```haskell
reify myLte $ \(_ :: Proxy p) ->
  let
     gumbo :: MinQueue (Named p Int)
     gumbo = fromList [ha, ha]
     yam = gumbo `union` gumbo
  in ...
```
