### ISSUE TITLE
Request: Addition to Stackage

### ISSUE THREAD

**Issue by asr** [lspitzner/pqueue#5]
We are planning to build Agda using Stackage. Please consider to add pqueue to Stackage. See  instructions [here](https://github.com/fpco/stackage#add-your-package).

**Comment by lspitzner** [comment]
i am planning to make a new minor release and put that on stackage, probably in the next week. Or would you rather me put the current version on stackage right away (i think it should work without modifications)?

**Comment by asr** [comment]
I can wait. Thanks!

**Comment by lspitzner** [comment]
in progress: https://github.com/fpco/stackage/pull/1945

**Comment by asr** [comment]
Thanks!
