### ISSUE TITLE
Data instances are unsafe/wrong

### ISSUE THREAD

**Issue by treeowl** [lspitzner/pqueue#50]
It strikes me as somewhat peculiar that we have `Data` instances for priority queues at all, but if we're to do so, they should be consistent!

```haskell
{-# language ScopedTypeVariables, GADTs, TypeOperators, TypeApplications #-}

import Data.Data
import Data.Typeable
import Data.PQueue.Min

morp :: MinQueue Int -> MinQueue Int
morp = gmapT go
  where
    go :: forall d. Data d => d -> d
    go d
      | Just Refl <- eqT @d @Int
      = abs d
      | Just Refl <- eqT @d @(MinQueue Int)
      = d

main = print $ morp $ fromList [-5 .. 5]
```

This prints

```
fromAscList [5,-4,-3,-2,-1,0,1,2,3,4,5]
```

What's happening here? The `Data` instance for `MinQueue` (roughly speaking) pretends that we have

```haskell
data MinQueue a = empty | a <| MinQueue a
```

(Yes, those "constructor" names are lower case on purpose; that's basically okay.) The user can edit the "minimum value" and "the rest of the queue" independently, and the `Data` instance just assumes that the new minimum is in fact now greater than the minimal element of the new rest of the queue. That's ... peculiar.

----

Now we get to the inconsistency. `Data.PQueue.Prio.Min` has a similarly peculiar but totally *different* view of the structure of a priority queue! Specifically, it pretends we have (roughly)

```haskell
data MinpQueue a b = MinPQueue [(a, b)]
```

(but blows up if you try to *construct* a `MinPQueue` using `gunfold` or to inspect one using `toConstr`). Bzzwhat?

----

`MaxQueue` and `MaxPQueue` each use *derived* `Data` instances. That means they inherit all the peculiarities of the underlying instances, as well as revealing the relationships between the queue types. But wait! There's more! The `Down` type used to implement those types *isn't exported from the package*. This makes anything `syb`-style on it a bit ... awkward.

### Solutions

The easiest solution is to delete all the `Data` instances. I know, I know, that could break things. Other things we could do:

- 1\. Structure the `MinPQueue` instance more like the `MinQueue` instance. I think the latter is much nicer (because it doesn't force the queue to be completely rebuilt for no reason).
- 2a\. Make the instances preserve the queue invariants.
- 2b\. Document that the instances don't preserve the queue invariants.
- 3a\. Make the `MaxQueue` and `MaxPQueue` instances look like the `MinQueue` and `MinPQueue` ones.
- 3b\. Expose the internal `Down` type.
- 4\. Document how the instances behave.

I'm leaning toward 1, 2a, 4, and possibly 3a. I don't like 3b because if https://github.com/haskell/core-libraries-committee/issues/23 is accepted we'll eventually want to switch to `Data.Ord.Down`. I'm slightly nervous about 3a because I don't think there's any inherent reason that `MaxQueue` and `MaxPQueue` must forever be abstract.

**Comment by treeowl** [comment]
Does anyone else have an opinion on this? We can do 4 and either 2a or 2b in a minor release; any of the rest of them will require a major release. I think we should do 4 and 2a in the next minor release (so we can get the perf improvements in without breaking things), and then do 1 and possibly 3a for the next major release.

**Comment by konsumlamm** [comment]
Disclaimer: I don't know much about `Data`.

I'd be fine with removing the instances (afaik, a `Data` instance for non-record-like types isn't really useful anyway) with a major version bump (i.e. to 1.5.0.0).

2a sounds good to me, I'd rather not make it easy to break the priority queue invariants. I think 3b is best solved by using `Data.Ord.Down` (but ig it's better to wait for haskell/core-libraries-committee#23). 4 should definitely be done, regardless of how we decide the instances should behave.

**Comment by treeowl** [comment]
I'm very far from a `Data` expert myself. Maybe @lspitzner has an opinion about whether it's worth having the instances at all. @konsumlamm, I suspect the main reason one might want them is to be able to use `Data`-based generic functions on datatypes that happen to include priority queues. For `MinPQueue` and `MaxPQueue`, it's even potentially sensible to edit the values. But like I said ... I don't really know. I find `Data` too confusing myself, and stick to `GHC.Generics` when I want to play in that kind of space.

**Comment by treeowl** [comment]
@RyanGlScott, I doubt you have any skin in this game, but I imagine you probably know more about `Data` uses and users than I do. Can you advise?

**Comment by RyanGlScott** [comment]
I'm not familiar with the code in this repo, but without knowing anything else, option 2a seems perfectly sensible to me. There is precedent for 2a for `Data` instances in `base`, such as in the [`Data` instance for `Ratio`](https://hackage.haskell.org/package/base-4.16.0.0/docs/src/Data.Data.html#line-1123), which uses a smart constructor rather than `Ratio`'s underlying data constructor.
