### ISSUE TITLE
Implement stimes

### ISSUE THREAD

**Issue by treeowl** [lspitzner/pqueue#54]
At a minimum, we want `stimes = stimesMonoid` so `stimes 0 whatever` is empty rather than bottom.

Can we do better? I doubt many (if any) will care, but I suspect so. When we calculate ``forest `union` forest``, all the trees we meld will be equal, so we don't have to compare any roots. Doing the multiplication by doubling manually should let us take advantage of that. But ... will anyone ever care?

**Comment by konsumlamm** [comment]
I agree, we definitely don't want `stimes 0 whatever` to be bottom. I can't think of a common use case where it's worth to optimize it further either.
