### ISSUE TITLE
Use `coerce` instead of `fmap unDown`/`fmap Down`

### ISSUE THREAD

**Issue by konsumlamm** [lspitzner/pqueue#97]
Since `Down` is a newtype, it's possible to use `coerce` instead of `fmap unDown`/`fmap Down`.

**Comment by treeowl** [comment]
Those are maps over lists, which should be rewritten to `coerce` by `RULES` in `GHC.base`.

**Comment by konsumlamm** [comment]
Yes, there's a rule for `map coerce`, but I'd rather not rely on that. In most cases it seems to be inlined, but there is at least one case where an `fmap Down` (on `Maybe`) is not optimized out.

**Comment by treeowl** [comment]
Interesting. There's no `fmap/coerce` rule for `Maybe`, but I'd have expected that `fmap` to inline. Why doesn't it?

**Comment by konsumlamm** [comment]
> Interesting. There's no `fmap/coerce` rule for `Maybe`, but I'd have expected that `fmap` to inline. Why doesn't it?

It does inline, but it doesn't reduce to `coerce`, it still matches the `Maybe`.

**Comment by treeowl** [comment]
How odd! That likely will get cleaned up in the Cmm, but I suggest filing a GHC ticket anyway. Just making sure: you're looking at the compiled code and not the unfolding, right?

**Comment by konsumlamm** [comment]
I'm looking at the core, I always supress the unfoldings anyway.

**Comment by treeowl** [comment]
So ... GHC ticket it is.

**Comment by treeowl** [comment]
Did you end up opening a GHC ticket for this, or shall I?

**Comment by konsumlamm** [comment]
I didn't, feel free to open one.
